#! /bin/bash -e

declare -a DELETES
TTL=600
FORCE=
IPREG="\([0-9]\+\.\)\{3\}[0-9]\+"
DNSREG="\([0-9a-z][0-9a-z-]\{0,63\}\.\)*[0-9a-z][0-9a-z-]\{0,63\}.\?"

function fqdn {
  local D=$1
  [ "${D%.}" = "$D" ] && D="${D}.${2%.}."
  echo -n "$D"
}

function defaults {
  ZONE=${ZONE:-$(dnsdomainname)}
  if [ "${ZONE}" -a "${ZONE}" != "(none)" ]; then
    DOMAIN=${DOMAIN:-${ZONE}}
    if [ ! "${SERVER}" ]; then
      _SERVER=$(dig +short -t NS "${ZONE}")
      if [ "$(echo "$_SERVER" | wc -l)" -gt 1 ]; then
        # it's usually not the case that multiple servers
        # can handle dynamic updates, but we would get
        # a random server
        # let's hope that $ZONE resolves to the host that
        # can handle updates
        SERVER=$ZONE
      else
        SERVER=$_SERVER
      fi
    fi
  else
    ZONE=
  fi
  RECORD=${RECORD:-$(hostname -s)}
  # make it fully qualified (add $DOMAIN)
  RECORD=$(fqdn "$RECORD" "$DOMAIN")
  [ ! "${VALUE_GIVEN}" ] && VALUE=$(curl -s icanhazip.com) || :

  # figure the record type if not specified
  if [ ! "${TYPE}" ]; then
    if echo "${VALUE}" | grep -q -e "^${IPREG}$"; then
      TYPE=A
    elif echo "${VALUE}" | grep -q -e "^${DNSREG}$" && [ "${#VALUE}" -lt 256 ]; then
      TYPE=CNAME
      # make it fully qualified (add $ZONE)
      VALUE=$(fqdn "$VALUE" "$ZONE")
    else
      TYPE=TXT
    fi
  fi
}

function uniq_args {

  FIRST=1
  for el in "$@"; do
    [ $FIRST -eq 0 ] && echo
    printf "%q" "$el"
    FIRST=0
  done
}

function usage {
  defaults
  PAD="
                  "
  fmt -s <<EOF
usage: dnskeyupdate [options] keyfile [zone]
  -d domain     domain to use in the record${DOMAIN:+${PAD}[${DOMAIN}]}
  -s server     dns server to update to${SERVER:+${PAD}[${SERVER}]}
  -t TTL        ttl for new record
                  [${TTL}]
  -x type       delete record of type, if type is ANY then all records
                  under '${RECORD}' (-r option) will be deleted.
                  Can be specified multiple times, each specified type
                  will be deleted.
  -T type       record type, defaults to A if value is an ip address,
                  CNAME if it contains a valid DNS name, otherwise TXT${TYPE:+${PAD}[${TYPE}]}
  -r record     the record name to update (default is hostname)
                  '${DOMAIN}' (-d option) is added if not fully qualified${RECORD:+${PAD}[${RECORD}]}
  -v value      override the value (defaults to \`icanhazip\`)
                  if value is a CNAME and not fully qualified, adds
                  '${ZONE}' (zone parameter)${VALUE:+${PAD}[${VALUE}]}
  -f            don't check first, update even if the records already
                  match
  -n            don't do any updates, just print out the nsupdate commands
  --show        show the values that would be used for an update (defaults
                  or specified in the options)
  [-k ]keyfile  the file with the private DNSSEC key, the only required
                  option on a well configured host
  [-z ]zone     zone to update record in, defaults to \`dnsdomainname\`
                  $([ "${ZONE}" ] && echo "[${ZONE}]" || echo "(required, you don't have a domain name configured)")

If type is a CNAME, the A record (if present) is deleted as well as any existing \
CNAME before adding the new CNAME record. Likewise if the type is A then both \
CNAME and A are deleted if present before updating.

zone is set to \`dnsdomainname\` by default. domain defaults to zone, and server \
defaults to the NS record for zone.

If specifying zone without the -z flag, you also have to specify key without the \
-k flag. Using the flags lets you place them anywhere in the arguments list.
EOF
  exit $1
}

function summary {
  defaults
  for p in ZONE SERVER TTL TYPE RECORD VALUE; do
    echo "${p}=${!p}"
  done
}

# bonafide options
while [ $# -gt 0 ]; do
  case $1 in
    -d) DOMAIN=$2; shift 2;;
    -s) SERVER=$2; shift 2;;
    -t) TTL=$2; shift 2;;
    -x) DELETES=("${DELETES[@]}" "$2"); VALUE=; VALUE_GIVEN=1; shift 2;;
    -T) TYPE=$2; shift 2;;
    -r) RECORD=$2; shift 2;;
    -v) VALUE=$2; VALUE_GIVEN=1; shift 2;;
    -f) FORCE=1; shift;;
    -n) DUMMY=1; shift;;
    -k) KEY=$2; shift 2;;
    -z) ZONE=$2; shift 2;;
    -h) HELP=0; shift;;
    --show) SUMMARY=1; shift;;
    -*) HELP=1; BADOPT=$1; set -- ; break;;
    *) OTHERARGS=("${OTHERARGS[@]}" "$1"); shift;;
    --) shift; break;;
  esac
done

set -- "${OTHERARGS[@]}" "$@"

KEY=${1:-$KEY}
ZONE=${2:-$ZONE}

if [ "${HELP}" ]; then
  [ "${HELP}" -eq 1 ] && echo "$0: Invalid option encountered: $BADOPT"
  usage "${HELP}"
fi

if [ "${SUMMARY}" ]; then
  summary
  exit
fi

defaults

# check if we need to change anything
# check value
if [ ! "${FORCE}" -a "${#DELETES[@]}" -eq 0 ]; then
  MY_RECORD=${TYPE}_RECORD
  # !MY_RECORD is an indirect reference, to take advantage of
  # records already fetched in the previous step
  MY_RECORD=${!MY_RECORD:-$(dig "@${SERVER}" -t ${TYPE} +short "${RECORD}")}
  MY_VALUE=${VALUE}
  if echo "${MY_RECORD}" | grep "^${MY_VALUE}$" > /dev/null ; then
    [ -t 1 ] && echo "Already up to date, exiting. ($MY_RECORD from $SERVER)"
    exit 0
  fi
fi

# there should only be an A or a CNAME, not both
if [ "${TYPE}" = "A" -o "${TYPE}" = "CNAME" -o "${TYPE}" = "AAAA" ]; then
  A_RECORD=$(dig "@${SERVER}" -t A "${RECORD}" +short)
  AAAA_RECORD=$(dig "@${SERVER}" -t AAAA "${RECORD}" +short)
  CNAME_RECORD=$(dig "@${SERVER}" -t CNAME "${RECORD}" +short)
  if [ "${TYPE}" = "CNAME" ]; then
    [ "${A_RECORD}" ] &&
    DELETES=("${DELETES[@]}" A)
    [ "${AAAA_RECORD}" ] &&
    DELETES=("${DELETES[@]}" AAAA)
    [ "${CNAME_RECORD}" ] &&
    DELETES=("${DELETES[@]}" CNAME)
  elif [ "${TYPE}" = "A" ]; then
    [ "${CNAME_RECORD}" ] &&
    DELETES=("${DELETES[@]}" CNAME)
    [ "${A_RECORD}" ] &&
    DELETES=("${DELETES[@]}" A)
  elif [ "${TYPE}" = "AAAA" ]; then
    [ "${CNAME_RECORD}" ] &&
    DELETES=("${DELETES[@]}" CNAME)
    [ "${AAAA_RECORD}" ] &&
    DELETES=("${DELETES[@]}" AAAA)
  fi
fi

# remove duplicates
eval DELETES=($(uniq_args "${DELETES[@]}"))

function nsupdate_text {
  echo "server ${SERVER}"
  echo "zone ${ZONE}"
  for t in "${DELETES[@]}"; do
    echo "update delete ${RECORD} ${t}"
  done
  if [ "${VALUE}" ]; then
    if [ "${TYPE}" = "TXT" ]; then
      echo "update add ${RECORD} ${TTL} ${TYPE} \"${VALUE}\""
    else
      echo "update add ${RECORD} ${TTL} ${TYPE} ${VALUE}"
    fi
  fi
  echo show
  echo send
}

if [ ! "${DUMMY}" ]; then
  nsupdate_text | tee /dev/stderr | nsupdate ${KEY:+-k "${KEY}"} -v
else
  nsupdate_text
fi
